name: .NET

on:
  push:
    branches: [ master, release/** ]
  pull_request:
    branches: [ master, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-StratusCube.Extensions.Configuration.RavenDB
        path: TestResults-StratusCube.Extensions.Configuration.RavenDB
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Pack
      run: dotnet pack -c Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./bin/Release/*.nupkg
        # The desired behavior if no files are found using the provided path.
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build]
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Download nupkg
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        path: ./artifacts
    - name: publish
      working-directory: ./artifacts
      run: dotnet nuget push ./artifacts/**/*.nupkg
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate --no-symbols
        -k ${NUGET_KEY}
      env:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
