name: .NET

on:
  push:
    branches: [ master, release/** ]
  pull_request:
    branches: [ master, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack -c Release
    - name: publish
      run: dotnet nuget push ./bin/Release/*.nupkg \
        -s --source https://api.nuget.org/v3/index.json \
        --skip-duplicate --no-symbols
        -k ${NUGET_API_KEY}
      env:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
